_commit: v0.4.73
_src_path: git@github.com:tschm/package.git
description: Export marimo notebooks in style
gh_create: gh repo create tschm/marimograd --public --description 'Export marimo notebooks
  in style'
page: https://tschm.github.io/marimograd
project_name: marimograd
repository: https://github.com/tschm/marimograd
ssh_uri: git@github.com:tschm/marimograd.git
status: public
use_dependabot: false
use_devcontainer: false
use_latex: false
use_renovate: true
username: tschm
