name: 'Marimushka Export Action'
description: 'Export marimo notebooks and apps to static HTML and WebAssembly for deployment to GitHub Pages or other static hosting'
author: 'Jebel Quant Research'
branding:
  icon: 'book'
  color: 'blue'

inputs:
  template:
    description: 'Path to a custom Jinja2 template file (.html.j2) for the index page. If not provided, the default Tailwind CSS template will be used.'
    required: false
  apps:
    description: 'Directory containing marimo app files (.py) to be exported as WebAssembly applications with hidden code (run mode).'
    required: false
    default: 'apps'
  notebooks:
    description: 'Directory containing marimo notebook files (.py) to be exported as static HTML notebooks.'
    required: false
    default: 'notebooks'
  notebooks_wasm:
    description: 'Directory containing marimo notebook files (.py) to be exported as interactive WebAssembly notebooks with editable code (edit mode).'
    required: false
    default: 'notebooks'


runs:
  using: "composite"
  steps:
    - name: 📦 Checkout repository
      uses: actions/checkout@v4

    - name: 🚀 Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: '3.12'
        cache-dependency-glob: '/dev/null'
        ignore-nothing-to-cache: 'true'

    - name: 🛠️ Export marimo notebooks to WebAssembly
      shell: bash
      run: |
        set -e  # Exit on error

        # Path to default template in this action's directory
        DEFAULT_TEMPLATE="${{ github.action_path }}/templates/tailwind.html.j2"

        # Use provided template if set, otherwise fallback
        if [ -z "${{ inputs.template }}" ]; then
          echo "No template provided. Using default: $DEFAULT_TEMPLATE"
          TEMPLATE="$DEFAULT_TEMPLATE"
        else
          echo "Using provided template: ${{ inputs.template }}"
          TEMPLATE="${{ inputs.template }}"
        fi

        # Output directory
        OUTPUT_DIR="artifacts/marimushka"
        mkdir -p "$OUTPUT_DIR"

        echo "Using template: $TEMPLATE"
        echo "Exporting to: $OUTPUT_DIR"
        echo "Apps: ${{ inputs.apps }}"
        echo "Notebooks: ${{ inputs.notebooks }}"
        echo "Notebooks-wasm: ${{ inputs.notebooks_wasm }}"

        uvx marimushka export \
          --template "$TEMPLATE" \
          --output "$OUTPUT_DIR" \
          --apps "${{ inputs.apps }}" \
          --notebooks "${{ inputs.notebooks }}"
          --notebooks_wasm "${{ inputs.notebooks_wasm }}"

        # Create .nojekyll file to prevent GitHub Pages from processing with Jekyll
        touch "$OUTPUT_DIR/.nojekyll"
        echo "Created .nojekyll file"

        echo "Publish the 'marimushka' artifact"
        tree artifacts/marimushka

    - name: 📤 Upload HTML artifacts
      uses: actions/upload-artifact@v4
      with:
        name: marimushka
        path: artifacts/marimushka
        retention-days: 1
