name: 'Export notebook using marimo'
description: 'Export of notebooks and apps'

inputs:
  template:
    description: 'html.j2 template for export'
    required: false

runs:
  using: "composite"
  steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: 🚀 Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.12'

      - name: 🛠️ Export notebooks to WebAssembly
        shell: bash
        run: |
          # Path to default template in this action's directory
          DEFAULT_TEMPLATE="${GITHUB_ACTION_PATH}/templates/default.html.j2"
  
          # Use provided template if set, otherwise fallback
          TEMPLATE="${{ inputs.template }}"
          if [ -z "$TEMPLATE" ]; then
            echo "No template provided. Using default: $DEFAULT_TEMPLATE"
            TEMPLATE="$DEFAULT_TEMPLATE"
          else
            echo "Using provided template: $TEMPLATE"
          fi
  
          uvx marimograd --template "$TEMPLATE"

      # Upload the generated site as an artifact for the deploy job
      - name: 📤 Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site  # Directory containing the built site
