name: 'Export marimo notebooks using marimushka'
description: 'Export of notebooks and apps'

inputs:
  template:
    description: 'The html.j2 template for export'
    required: false
  apps:
    description: 'The folder for applications'
    required: false
    default: 'apps'
  notebooks:
    description: 'The folder for plain html notebooks'
    required: false
    default: 'notebooks'
  notebooks_wasm:
    description: 'The folder for interactive notebooks'
    required: false
    default: 'notebooks'

runs:
  using: "composite"
  steps:
    - name: 📦 Checkout repository
      uses: actions/checkout@v4

    - name: 🚀 Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: '3.12'
        cache-dependency-glob: '/dev/null'
        ignore-nothing-to-cache: 'true'

    - name: 🛠️ Export marimo notebooks to WebAssembly
      shell: bash
      run: |
        set -e  # Exit on error

        # Path to default template in this action's directory
        DEFAULT_TEMPLATE="${{ github.action_path }}/template/tailwind.html.j2"

        # Use provided template if set, otherwise fallback
        if [ -z "${{ inputs.template }}" ]; then
          echo "No template provided. Using default: $DEFAULT_TEMPLATE"
          TEMPLATE="$DEFAULT_TEMPLATE"
        else
          echo "Using provided template: ${{ inputs.template }}"
          TEMPLATE="${{ inputs.template }}"
        fi

        # Output directory
        OUTPUT_DIR="/tmp/marimushka"
        mkdir -p "$OUTPUT_DIR"

        echo "Using template: $TEMPLATE"
        echo "Exporting to: $OUTPUT_DIR"
        echo "Apps: ${{ inputs.apps }}"
        echo "Notebooks: ${{ inputs.notebooks }}"
        echo "Publish: ${{ inputs.publish }}"

        uvx marimushka compile \
          --template "$TEMPLATE" \
          --output "$OUTPUT_DIR" \
          --apps "${{ inputs.apps }}" \
          --notebooks "${{ inputs.notebooks }}"

        # Create .nojekyll file to prevent GitHub Pages from processing with Jekyll
        touch "$OUTPUT_DIR/.nojekyll"
        echo "Created .nojekyll file"
        
        echo "Publish the 'marimo' artifact"


    - name: 📤 Upload HTML artifacts
      uses: actions/upload-artifact@v4
      with:
        name: marimo
        path: /tmp/marimushka
        retention-days: 1
