name: 'Export marimo notebooks using marimushka'
description: 'Export of notebooks and apps'

inputs:
  template:
    description: 'The html.j2 template for export'
    required: false
  apps:
    description: 'The apps folder'
    required: false
  notebooks:
    description: 'The notebooks folder'
    required: false

runs:
  using: "composite"
  steps:
    - name: 📦 Checkout repository
      uses: actions/checkout@v4

    - name: 🚀 Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: '3.12'
        cache-dependency-glob: '/dev/null'
        ignore-nothing-to-cache: 'true'

    - name: 🛠️ Export marimo notebooks to WebAssembly
      shell: bash
      run: |
        set -e  # Exit on error

        # Path to default template in this action's directory
        DEFAULT_TEMPLATE="${GITHUB_ACTION_PATH}/templates/default.html.j2"

        # Use provided template if set, otherwise fallback
        if [ -z "${{ inputs.template }}" ]; then
          echo "No template provided. Using default: $DEFAULT_TEMPLATE"
          TEMPLATE="$DEFAULT_TEMPLATE"
        else
          echo "Using provided template: ${{ inputs.template }}"
          TEMPLATE="${{ inputs.template }}"
        fi

        # Output directory
        OUTPUT_DIR="/tmp/marimushka"
        mkdir -p "$OUTPUT_DIR"

        echo "Using template: $TEMPLATE"
        echo "Exporting to: $OUTPUT_DIR"
        echo "Apps: ${{ inputs.apps }}"
        echo "Notebooks: ${{ inputs.notebooks }}"

        uvx marimushka \
          --template "$TEMPLATE" \
          --output "$OUTPUT_DIR" \
          --apps "${{ inputs.apps }}" \
          --notebooks "${{ inputs.notebooks }}"

    - name: 📂 Check the output structure
      shell: bash
      run: |
        echo "Output directory contents:"
        tree /tmp/marimushka || echo "(tree not installed)"

    - name: 📤 Upload HTML artifacts
      if: ${{ env.ACT != 'true' }}  # Skip if running with 'act'
      uses: actions/upload-artifact@v4
      with:
        name: marimo
        path: /tmp/marimushka
        retention-days: 1