# Workflow for running Python tests
# This workflow runs pytest on multiple Python versions and also tests the Makefile

name: Python Tests

on:
  # Trigger the workflow on push events
  push

jobs:
  # Job to run pytest on multiple Python versions
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest

    # Test on multiple Python versions to ensure compatibility
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      # Check out the repository code
      - uses: actions/checkout@v4

      # Set up Python environment using uv with the specified version
      - name: Set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      # Install project dependencies
      - name: Install dependencies
        run: |
          uv venv
          uv pip install --upgrade pip
          uv sync --all-extras

      # Run pytest with coverage reporting
      - name: Run tests
        run: |
          uv run pytest src/tests/ -v --cov=src/marimushka

  # Job to test the Makefile's test target
  make:
    name: Run tests via make
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - uses: actions/checkout@v4

      # Run tests using the Makefile to ensure it works correctly
      - name: Run via Makefile
        run: |
          make test
