# GitHub Actions workflow for testing the Marimushka export action
# This workflow tests various aspects of the Marimushka export functionality:
# - Exporting only notebooks (no apps)
# - Verifying template file existence
# - Testing the CLI help command

name: "ACTION"

on:
  push:  # Trigger on push events to run tests automatically

permissions:
  contents: write  # Write access to repository contents for GitHub Pages deployment

jobs:
  # Job to test exporting only notebooks (no apps)
  test-only-notebooks:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      # Step 2: Test the export action with only notebooks (no apps)
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: ./actions/export
        with:
          # Only specify the notebooks folder, leave apps empty to test that scenario
          notebooks: 'src/tests/resources/notebooks'
          apps: ''
          #template: 'src/tests/resources/templates/tailwind.html.j2'


  book:
    runs-on: ubuntu-latest
    needs: test-only-notebooks
    permissions:
      contents: write

    steps:
      # Step 1: Download the marimo artifact
      # This step downloads the artifact created by the export action
      - name: Download marimo artifact
        uses: actions/download-artifact@v4
        with:
          path: book

      # Step 2: Verify the downloaded artifact
      - name: Verify downloaded artifact
        run: |

          echo "🔍 Verifying artifacts..."

          # Define the files to check
          required_files=(
            "book/marimushka/index.html"
            "book/marimushka/notebooks/fibonacci.html"
            "book/marimushka/notebooks/penguins.html"
          )

          # Check each file
          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing required file: $file"
              echo "📂 Current directory: $(pwd)"
              echo "📄 Listing artifacts/marimushka:"
              ls -l book/marimushka || echo "❓ Directory not found"
              echo "📄 Listing artifacts/marimushka/notebooks:"
              ls -l book/marimushka/notebooks || echo "❓ Directory not found"
              exit 1
            else
              echo "✅ Found: $file"
            fi
          done

          echo "🎉 All required artifacts are present."

  # Job to test the CLI help command
  help:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      # Step 2: Set up a Python environment using uv
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13

      # Step 3: Display the help screen to verify CLI functionality
      - name: Display help
        run: |
          uv run marimushka --help
          uvx marimushka --help
          uvx marimushka

      - name: Display help export
        run: |
          uv run marimushka export --help
          uvx marimushka export --help

      - name: Display version
        run: |
          uv run marimushka version
          uvx marimushka version
