# GitHub Actions workflow for testing the Marimushka export action
# This workflow tests various aspects of the Marimushka export functionality:
# - Exporting only notebooks (no apps or notebooks_wasm)
# - Exporting with all inputs (notebooks, apps, notebooks_wasm)
# - Exporting with a custom template
# - Error handling with non-existent directories

name: Test Marimushka Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Test with all inputs (notebooks, apps, notebooks_wasm)
  test-all-inputs:
    name: Test with all inputs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run action with all inputs
        uses: ./
        with:
          notebooks: 'src/tests/resources/notebooks'
          apps: 'src/tests/resources/apps'
          notebooks_wasm: 'src/tests/resources/notebooks_wasm'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: marimushka
          path: /tmp/all-inputs

      - name: Verify artifact
        run: |
          tree /tmp/all-inputs
          
          echo "🔍 Verifying all-inputs artifacts..."

          # Check if index.html exists
          if [ ! -f "/tmp/all-inputs/index.html" ]; then
            echo "❌ Missing index.html"
            exit 1
          else
            echo "✅ Found index.html"
          fi

          # Check if all directories exist
          for dir in "notebooks" "apps" "notebooks_wasm"; do
            if [ ! -d "/tmp/all-inputs/$dir" ]; then
              echo "❌ Missing $dir directory"
              exit 1
            else
              echo "✅ Found $dir directory"
            fi
          done

          # List all files in the artifact
          echo "📄 Files in the artifact:"
          find /tmp/all-inputs -type f | sort
