# GitHub Actions workflow for continuous integration
# This workflow runs tests on multiple operating systems and Python versions

name: "ACTION"

on:
  push:  # Trigger on push events

permissions:
  contents: read  # Read-only access to repository contents

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      # Step 2: Build the virtual environment with the specified Python version
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: ./actions/export
        with:
          notebooks: 'src/tests/resources/notebooks'
          apps: 'src/tests/resources/apps'
          template: 'src/tests/resources/templates/default.html.j2'


  test-only-notebooks:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      # Step 2: Build the virtual environment with the specified Python version
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: ./actions/export
        with:
          notebooks: 'src/tests/resources/notebooks'



  template:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      # Step 2: Check if the template file exists
      - name: Check template file exists
        run: |
          if [ ! -f src/tests/resources/templates/default.html.j2 ]; then
            echo "❌ Template file not found!"
            exit 1
          else
            echo "✅ Template file found."
          fi

  help:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13

      # Step 2: Display the help screen
      - name: Display help
        run: |
          uv run marimushka --help
